//  APP RELATED
export const RESET_APP = 'RESET_APP';

//  VIDEOS
export const VIDEOS_REQUEST = 'VIDEOS_REQUEST';
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCESS';
export const VIDEOS_FAILURE = 'VIDEOS_FAILURE';
export const VIDEOS_RESET = 'VIDEOS_RESET';

//  CATS
export const CATS_REQUEST = 'CATS_REQUEST';
export const CATS_SUCCESS = 'CATS_SUCCESS';
export const CATS_FAILURE = 'CATS_FAILURE';
export const CATS_RESET = 'CATS_RESET';

//  SINGLE CAT
export const CAT_REQUEST = 'CAT_REQUEST';
export const CAT_SUCCESS = 'CAT_SUCCESS';
export const CAT_FAILURE = 'CAT_FAILURE';
export const CAT_RESET = 'CAT_RESET';

//  IMAGES
export const IMAGES_REQUEST = 'IMAGES_REQUEST';
export const IMAGES_SUCCESS = 'IMAGES_SUCCESS';
export const IMAGES_FAILURE = 'IMAGES_FAILURE';
export const IMAGES_RESET = 'IMAGES_RESET';

//  SINGLE IMAGE
export const IMAGE_REQUEST = 'IMAGE_REQUEST';
export const IMAGE_SUCCESS = 'IMAGE_SUCCESS';
export const IMAGE_FAILURE = 'IMAGE_FAILURE';
export const IMAGE_RESET = 'IMAGE_RESET';

//  RELATED IMAGES
export const RELATED_IMAGES_REQUEST = 'RELATED_IMAGES_REQUEST';
export const RELATED_IMAGES_SUCCESS = 'RELATED_IMAGES_SUCCESS';
export const RELATED_IMAGES_FAILURE = 'RELATED_IMAGES_FAILURE';
export const RELATED_IMAGES_RESET = 'RELATED_IMAGES_RESET';